# Configuration for Label Actions - https://github.com/dessant/label-actions

# The `feature` label is added to issues
feature:
  issues:
    # Post a comment, `{issue-author}` is an optional placeholder
    comment: >
      :wave: @{issue-author}, please use our idea board to request new features.
    # Close the issue
    close: true

# The `solved` label is added to discussions
solved:
  discussions:
    # Lock the discussion
    lock: true


"Status: Repro Missing":
  comment: >
    Hello @{issue-author},
    thank you for your submission. The issue was labelled "Status: Repro Missing", as you have not provided a way to quickly reproduce the issue. Most problems already solve themselves when isolated and if they don't, you will have made it easier for the maintainer of this project to investigate a possible bug.
